---
- name: Download file using aria2c
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install aria2
      apt:
        name: aria2
        state: present

    - name: Download file
      become: yes
      command: aria2c --file-allocation=none "https://www.mysite.com/apple.jpg"

